/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AlleventsRouteImport } from './routes/allevents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetregistrationIdRouteImport } from './routes/getregistration/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AlleventsRoute = AlleventsRouteImport.update({
  id: '/allevents',
  path: '/allevents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetregistrationIdRoute = GetregistrationIdRouteImport.update({
  id: '/getregistration/$id',
  path: '/getregistration/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allevents': typeof AlleventsRoute
  '/register': typeof RegisterRoute
  '/getregistration/$id': typeof GetregistrationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allevents': typeof AlleventsRoute
  '/register': typeof RegisterRoute
  '/getregistration/$id': typeof GetregistrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allevents': typeof AlleventsRoute
  '/register': typeof RegisterRoute
  '/getregistration/$id': typeof GetregistrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/allevents' | '/register' | '/getregistration/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allevents' | '/register' | '/getregistration/$id'
  id: '__root__' | '/' | '/allevents' | '/register' | '/getregistration/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlleventsRoute: typeof AlleventsRoute
  RegisterRoute: typeof RegisterRoute
  GetregistrationIdRoute: typeof GetregistrationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allevents': {
      id: '/allevents'
      path: '/allevents'
      fullPath: '/allevents'
      preLoaderRoute: typeof AlleventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getregistration/$id': {
      id: '/getregistration/$id'
      path: '/getregistration/$id'
      fullPath: '/getregistration/$id'
      preLoaderRoute: typeof GetregistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlleventsRoute: AlleventsRoute,
  RegisterRoute: RegisterRoute,
  GetregistrationIdRoute: GetregistrationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
